### PR TITLE
Unclear UI on quality definitions page 

### LINKED ISSUE #477: Unclear UI on quality definitions page
**Describe the bug**
The UI leaves "kilobits per second" visible even when the boxes are hidden as per the "advance features" setting. This led me to raise issue #476 in error. The real issue appears to be unclear UI.

**Expected behavior**
The heading text to be hidden along with the controls when advanced options is off.

### PR DESCRIPTION
**Pull request by gismo2004**
#### Issues Fixed or Closed by this PR
Unclear UI on quality definitions page #477

Fixes #477

### CODE REVIEW

**Comment by Qstick** [comment]
Build failing due to indent issue. One hint, Run `yarn eslint` and `yarn stylelint` to check ui formatting before pushing.

File: frontend/src/Settings/Quality/Definition/QualityDefinitions.js [hunk 1]
```diff
@@ -26,7 +27,9 @@ class QualityDefinitions extends Component {
             <div className={styles.quality}>Quality</div>
             <div className={styles.title}>Title</div>
             <div className={styles.sizeLimit}>Size Limit</div>
-            <div className={styles.kilobitsPerSecond}>Kilobits Per Second</div>
+            {advancedSettings &&
+                <div className={styles.kilobitsPerSecond}>Kilobits Per Second</div>
```
Comment (Qstick) [inline frontend/src/Settings/Quality/Definition/QualityDefinitions.js]: Indent format is 2 spaces.

**Comment by gismo2004** [comment]
Thx for the hint! i have pushed a fixed version.
