### PR TITLE
Fixed: Disable update for docker containers

### LINKED ISSUE #628: Disable built in update when running in docker
It's not good practice to update an application in a docker container.

https://stackoverflow.com/questions/26734402/how-to-upgrade-docker-container-after-its-image-changed/46181627

#617 adds detection of a docker environment.should we use that to disable the inbuilt update?

### PR DESCRIPTION
**Pull request by ta264**
#### Database Migration
NO

#### Description
Prevent Lidarr from updating inside a docker container.  Also note that docker is being used in the about page and sentry context.

#### Issues Fixed or Closed by this PR

* Fixes #628

### CODE REVIEW

File: frontend/src/Settings/General/GeneralSettings.js [hunk 1]
```diff
@@ -157,12 +158,15 @@ class GeneralSettings extends Component {
...
                 />
 
-                <UpdateSettings
-                  advancedSettings={advancedSettings}
-                  settings={settings}
-                  isMono={isMono}
-                  onInputChange={onInputChange}
-                />
+                {
+                  !isDocker &&
```
Comment (Qstick) [inline frontend/src/Settings/General/GeneralSettings.js]: Instead of completely not showing the section, should we instead disable everything and show a warning that updating is done via the container?

**Comment by Qstick** [comment]
Add test to `UpdateServiceFixture.cs` should_not_update_if_inside_docker_container?

File: frontend/src/Settings/General/GeneralSettings.js (hunk 1 above)
Comment (ta264) [reply frontend/src/Settings/General/GeneralSettings.js]: It'll show a message in the update page if an update is available: `An update is available.  Please update your Docker image and re-create the container.`

Shall I put the same thing in here?

Comment (Qstick) [reply frontend/src/Settings/General/GeneralSettings.js]: I'd just show "updating is disabled on docker" or something simple on the settings page under the update header. The updates page message looks good.

**Comment by ta264** [comment]
Test added.  Had to make the `IsDocker` not static and move it into `IOsInfo` so that we can mock but I think breaking the symmetry with `IsWindows` etc is worth it for the testability.
